---
title: "Experience"
---

\

# Research Experience

## Mcs Internship | The Learning Brain Lab, KU Leuven
### Ongoing
#### Supervised by Dr. Mila Marinova and Professor Bert Reynvoet
Examining the Integration of Numerical Formats Using EEG: Using HMP and DDM to model decision making processes in numerosity tasks from EEG data; Bayesian analyses; planned poster presentations and conference attendence. 


## Research Assistant | Neuroendocrinology Lab, SUNY Oswego
#### Supervised by Professor Gilian Tenbergen
Gathered literature overview of 2D:4D digit ratio; assessed literature and identified gaps in knowledge; collected data using hand scans and paper surveys; analyzed data using IBM SPSS; expressed results in the form of a written paper and oral presentation.## Research Assistant | Social Psychology Lab

\

## Research Assistant | Cognitive Neuroscience Lab, SUNY Oswego
#### Supervised by Professor Sien Hu
Obtained safety certification for fMRI usage at the University of Rochester; developed an experimental process for examining mental rotation.

\

#### Supervised by Professor Adam Fay, SUNY Oswego
Created spreadsheets in Excel; analyzed archival exam data on clicker usage in lecture halls; followed inter-rater reliability protocols; developed hypotheses; utilized IBM SPSS for data analysis.

\

# Leadership Positions

## Teaching Assistant for Research Methods for the Psychological Sciences | SUNY Oswego
Facilitated class discussions; held office hours; assisted students with lab work and questions; developed and ran review sessions.

\

## Queer and Trans Outreach Center
Built and maintained a database of campus and community LGBTQ+ resources; facilitated group discussions and educational activities for students and faculty; planned and led workshops for faculty; worked with administration to develop school policy regarding gender neutral restrooms, preferred names, and faculty training initiatives.

\

## Children’s International Summer Villages (CISV)
Participated in and facilitated various local, national, and international peace education programs; developed and ran educational activities about human rights, conflict resolution, sustainability, and diversity; managed planning groups; created guidelines and surveys to monitor policies and content across international chapters as a part of the Gender, Sexuality, and Romantic Diversity Inclusion (GSRDI) International Working Group; staffed a 2-week educational summer program for 12-13 year olds from 8 different countries.






